version: '2'
services:
  mdb:
    image: mongo:3.6
    restart: always
    container_name: mdb
    volumes:
      - mongo:/data/db
    networks:
      - db_net
  aut:
    image: picazica/aut
    container_name: aut
    ports:
      - '4000:4000'
    networks:
      - db_net
      - aut_net
  email:
    image: picazica/mail
    container_name: email
    ports:
      - '9000:9000'
    networks:
      - aut_net
      - server_net
  smtp:
    image: namshi/smtp:latest
    container_name: smtp
    restart: always
    ports:
      - '25:25'
    networks:
      - server_net
networks:
  db_net:
    driver: bridge
  aut_net:
    driver: bridge
  server_net:
    driver: bridge
volumes:
  mongo: 
    driver: local